version: '3.1'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: sa
      MONDGO_INITDB_DATABASE: rule-engine
    ports:
      - "27017:27017"